name: My First Pipeline
on: [push]

jobs:
  inspect-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, World! I am running on a github server"
      - name: Check System Info
        run: |
          echo "the operating system is:"
          lsb_release -a
          echo "the current directory is:"
          pwd
          echo "the python version installed is:"
          python3 --version