name: My First Pipeline
on: [push]

jobs:
  inspect-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Check System Info
        run: |
          echo "the operating system is:"
          lsb_release -a
          echo "the current directory is:"
          pwd
          echo "the python version installed is:"
          python3 --version


      - name: Checkout Code
        uses: actions/checkout@v4


      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Run my Python test
        run: python app.py
